name: Django CI/CD

on:
  push:
    branches:
      - "**"
      #- main

env:
  REGISTRY_IMAGE: ghcr.io/${{ github.repository_owner }}/fare-calculator-service
  APP_NAME: fare-calculator-service
  HEALTH_DELAY: ${{ secrets.DEPLOY_DELAY }}
  CONTAINER_NAME: fare-calculator-service

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Apply Migration
        #continue-on-error: true
        run: |
          python manage.py makemigrations --merge --noinput
          python manage.py migrate

      - name: Run Tests
        #continue-on-error: true
        run: |
          python manage.py test

  build:
    needs: tests
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        run: |
          echo "${{ secrets.PERSONAL_ACCESS_TOKEN }}" | docker login ghcr.io -u ${{ secrets.REGISTRY_NAMESPACE }} --password-stdin

      - name: Build Docker image
        run: |
          echo "Building Docker image..."
          docker build -t ${{ env.REGISTRY_IMAGE }}:latest .

      - name: Push Docker image
        run: |
          echo "Pushing Docker image..."
          docker push ${{ env.REGISTRY_IMAGE }}:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Copy docker-compose.yml to server
        run: |
          scp -o StrictHostKeyChecking=no docker-compose.yml ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}:/root/projet_synthese/infra/docker-compose.yml

      - name: Deploy on server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} << 'EOF'

            echo "Pulling latest image ${{ env.REGISTRY_IMAGE }}"

            docker login ghcr.io -u ${{ secrets.REGISTRY_NAMESPACE }} -p ${{ secrets.PERSONAL_ACCESS_TOKEN }}

            cd /root/projet_synthese/infra

            echo "Stopping all services"
            docker compose down

            echo "Removing old image"
            docker rmi -f ${{ env.REGISTRY_IMAGE }}:latest || true

            echo "Pulling new image"
            docker pull ${{ env.REGISTRY_IMAGE }}:latest

            echo "Starting ALL services (db, redis, app, celery)"
            docker compose up -d db redis
            
            echo "Waiting 10s for database to be ready..."
            sleep 10
            
            docker compose up -d fare-calculator-service celery_worker celery_beat

            echo "Waiting ${{ env.HEALTH_DELAY }} seconds for health check"
            sleep ${{ env.HEALTH_DELAY }}

            echo "Checking container health..."
            STATUS=$(docker inspect --format='{{json .State.Health.Status}}' ${{ env.CONTAINER_NAME }})

            echo "Health status: $STATUS"

            if [ "$STATUS" != "\"healthy\"" ]; then
              echo "ERROR: Container is not healthy"
              echo "--- Container logs ---"
              docker logs ${{ env.CONTAINER_NAME }} --tail 50
              exit 1
            fi

            echo "Deployment successful & container healthy!"
          EOF
